export * from './schema'
export { useDocumentStore, type Selection } from './store/document'
export { BUILDER_PINIA_KEY, useBuilderPinia } from './store/keys'
export { renderHtml, escapeHtml, SOCIAL_BRANDS } from './render/html'
export { default as EmailBuilder } from './components/EmailBuilder.vue'
export { useUiStore } from './store/ui'
export { type BuilderOptions, type MergeTagDef, BUILDER_OPTIONS_KEY, useBuilderOptions } from './options'
export { BUILTIN_TEMPLATES, type EmailTemplate } from './templates'
